import {Simpson} from "./Simpson";

const Simpsons = () => {
    let simpsonsArray = [
        {id:1,name:'Homer',bio: 'Homer Jay Simpson (born May 12, 1956) is the main protagonist of the The Simpsons. He is the husband of Marge Simpson and father of Bart, Lisa and Maggie Simpson. Homer is overweight (said to be 240 pounds elsewhere[39]),[6] lazy, and often ignorant to the world around him. Although he has many flaws, he has shown to have great caring, love and even bravery to those he cares about and sometimes, even others he doesn\'t.',age:'40', image:'https://media.npr.org/assets/img/2014/05/08/simp2006_homerarmscrossed_f_custom-ec94cc7a10463aa8260b2c5a9a3ebea29c7ecbfe-s1100-c50.jpg'},
        {id:2,name:'Marge',bio:'Marjorie Jacqueline "Marge" Simpson (née Bouvier)[11](Born March 19) is the homemaker and matriarch of the Simpson family. She is also one of the five main characters in The Simpsons TV series. She and her husband Homer have three children: Bart, Lisa, and Maggie. Marge is the moralistic force in her family and often provides a grounding voice in the midst of her family\'s antics by trying to maintain order in the Simpson household. Aside from her duties at home, Marge has flirted briefly with a number of careers ranging from a police officer to an anti-violence activist.', age:'35', image:'https://i.discogs.com/WI38UGun7TKKNg04MTHK0yV-I1Yb75sdJ_t0GEermmo/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTI2MzMx/MzAtMTMzNTcyMDM5/MC5wbmc.jpeg'},
        {id:3,name:'Bart',bio:'Bartholomew JoJo "Bart" Simpson (born April 1 ,1979 or February 23, 1979) is the mischievous, rebellious, misunderstood, disruptive and "potentially dangerous" oldest child of the Simpson family in The Simpsons. He is the only son of Homer and Marge Simpson, and the older brother of Lisa and Maggie. He also has been nicknamed "Cosmo", after discovering a comet in "Bart\'s Comet". Bart has also been on the cover on numerous comics, such as "Critical Hit", "Simpsons Treasure Trove #11", and "Winter Wingding". Bart also has a 100-issue comic series entitled the Simpson Comics Presents Bart Simpson. Bart is loosely based on Matt Groening and his older brother, Mark Groening.', age:'12', image:'https://upload.wikimedia.org/wikipedia/en/a/aa/Bart_Simpson_200px.png'},
        {id:4,name:'Lisa',bio:'Lisa Marie Simpson is the elder daughter and middle child of the Simpson family and one of the two tritagonists (along with Marge,) of The Simpsons. She was named after a train called Lil\' Lisa on her parents\' 1st anniversary.[10] In "Homer and Lisa Exchange Cross Words", she called herself Lisa Bouvier after estranging herself from her father after he bet against her in a crossword tournament.', age:'7', image:'https://upload.wikimedia.org/wikipedia/en/e/ec/Lisa_Simpson.png'},
        {id:5,name:'Meggie',bio:'Margaret Lenny "Maggie" Simpson is the 1-year-old daughter and youngest child of Marge and Homer Simpson, the baby sister to Bart and Lisa Simpson and one of the five main characters of The Simpsons. She is often seen sucking on her pacifier, and when she walks, she trips over her clothing and falls on her face. Because she rarely ever talks, Maggie is the least seen and heard in the Simpson family. Maggie is at the very young, infant age of 1.', age:'3', image:'https://static.simpsonswiki.com/images/thumb/9/9d/Maggie_Simpson.png/250px-Maggie_Simpson.png'}
    ]
    return (
        <div>
            {simpsonsArray.map(simpson => <Simpson simpson={simpson} key={simpson.id}/>)}
        </div>
    );
};

export {Simpsons};